package org.panashe.bible

import org.panashe.bible.features.communion.CommunionGenerator
import org.panashe.bible.shared.ScriptureReference
import org.panashe.bible.shared.SharedRules
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Locks CommunionGenerator to panashe-bible-web's communion-seed.js algorithm.
 *
 * Fixture: 2 books -> flat chapter list [a1, a2, a3, b1, b2] (size 5); a single
 * seed theme -> reference pool [a1:1, a2:1] (size 2). Each day consumes seven
 * slots; once the pool is exhausted, references are generated by walking the
 * flat chapter list at (index * 7 + offset) mod 5. Expectations are derived by
 * hand and verified to match web for the real corpus (index 20 -> Numbers 24:1).
 */
class CommunionGeneratorTest {
    private val manifest = BibleManifest(
        translation = TranslationInfo("KJVA", "kjva", "King James Version with Apocrypha"),
        books = listOf(
            BookSummary(index = 0, name = "Alpha", slug = "a", chapters = 3, section = "Old Testament"),
            BookSummary(index = 1, name = "Beta", slug = "b", chapters = 2, section = "Old Testament"),
        ),
    )

    private fun ref(book: String, chapter: Int) =
        SharedRules.canonicalReference(book, chapter, 1, 1)

    private val seed = CommunionSeed(
        startIso = "2026-06-01",
        endIso = "2026-06-03",
        themes = listOf(
            org.panashe.bible.CommunionTheme(
                gathered = ref("a", 1),
                offerings = listOf(ref("a", 2)),
            ),
        ),
    )

    private val generator = CommunionGenerator(manifest, seed)

    private fun key(reference: ScriptureReference) = SharedRules.referenceKey(reference)

    @Test
    fun dateMath() {
        assertEquals(0, generator.dayIndexForIso("2026-06-01"))
        assertEquals(20, generator.dayIndexForIso("2026-06-21"))
        assertEquals("2026-06-01", generator.isoForIndex(0))
        assertEquals("2026-06-03", generator.isoForIndex(2))
        assertEquals(3, generator.totalDays)
    }

    @Test
    fun day0DrawsFromSeedPool() {
        // poolIndex 0 -> pool[0] (a1); poolIndex 1 -> pool[1] (a2); rest generated.
        val day = generator.communionForDate("2026-06-01")
        assertEquals(0, day.index)
        assertEquals(key(ref("a", 1)), key(day.gathered))
        assertEquals(key(ref("a", 2)), key(day.offerings.first()))
    }

    @Test
    fun fallbackGeneratesByChapterWalk() {
        // index 1: every slot is past the 2-entry pool, so all are generated.
        // gathered slot = (1*7+0) % 5 = 2 -> chapters[2] = a3.
        // offering slots = 8,9,10,11,12,13 mod 5 = 3,4,0,1,2 -> b1,b2,a1,a2,a3.
        val day = generator.communionForDate("2026-06-02")
        assertEquals(1, day.index)
        assertEquals(key(ref("a", 3)), key(day.gathered))
        assertEquals(
            listOf("b" to 1, "b" to 2, "a" to 1, "a" to 2, "a" to 3).map { key(ref(it.first, it.second)) },
            day.offerings.map { key(it) },
        )
    }

    @Test
    fun datesPastSeedRangeClampToLastDay() {
        val day = generator.communionForDate("2030-01-01")
        assertEquals(generator.totalDays - 1, day.index)
    }
}
